### ISSUE TITLE
US#01 - Task#01 - Criar Modelo Conceitual

### ISSUE THREAD

**Issue by joaopaulo164** [stepesbd/ipbl2020#14]
Criar Modelo Conceitual do Banco de Dados do Hospital

**Comment by oswaldocostaneto** [comment]
Boa noite, pessoal. Trabalhamos hoje num esboço do Modelo Conceitual e Lógico. Gostariamos que opinassem quanto à possíveis modificações. Segue também o arquivo editável para caso queiram realizar alterações (brModelo).

![mod_conc_v1](https://user-images.githubusercontent.com/50557641/78310790-59db3780-7525-11ea-8ddf-053e385c6b49.jpg)

[Hospital_v1.zip](https://github.com/stepesbd/ipbl2020/files/4424384/Hospital_v1.zip)
