### ISSUE TITLE
US#02 - Task03 - Modelar o Banco de Dados

### ISSUE THREAD

**Issue by engcompjuliana** [stepesbd/ipbl2020#37]

**Comment by RENATABR** [comment]
Assumindo tarefa.

**Comment by RENATABR** [comment]
ASSUMINDO TAREFA

**Comment by RENATABR** [comment]
PRIMEIRA VERSAO MODELO COMITADO

**Comment by RENATABR** [comment]
[https://drive.google.com/drive/folders/12OJp0PsvXrZ9OTqqMwju7jqbP27ep05p](url)
